apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dsp-capita-cert
spec:
  secretName: dsp-capita-cert-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - deltacapita.com
    - clients.api.deltacapita.com