---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsp-api
spec:
  replicas: 3  # Multiple replicas for high availability
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: dsp-api
  template:
    metadata:
      labels:
        app: dsp-api
    spec:
      containers:
      - name: dsp-api
        image: dineshpundkar/client_api:v2.0
        imagePullPolicy: Always
        env:
        - name: MONGODB_HOST
          value: "mongodb"
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_DATABASE
          value: "clientdb"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/clientdb"
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: dsp-api
spec:
  selector:
    app: dsp-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  type: ClusterIP
